# Generated by Django 6.0.3 on 2026-08-08 15:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('questions', '0002_codetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesession',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_code', models.TextField(blank=True)),
                ('language', models.CharField(max_length=50)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.candidatesession')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
