# Generated by Django 6.0.3 on 2026-08-08 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript')], max_length=20)),
                ('starter_code', models.TextField()),
            ],
            options={
                'ordering': ['language'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_company',
        ),
        migrations.AddField(
            model_name='category',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='question',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('name', 'company'), name='unique_category_per_company'),
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_templates', to='questions.question'),
        ),
        migrations.AlterUniqueTogether(
            name='codetemplate',
            unique_together={('question', 'language')},
        ),
    ]
